when:
  branch: main
  event: [push, pull_request]

steps:
  maven_build:
    image: maven:3.9.11-amazoncorretto-21-al2023
    commands:
      - mvn -B -ntp clean package

  build_push_image:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      USERNAME:
        from_secret: GHCR_USERNAME
      TOKEN:
        from_secret: GHCR_TOKEN
    commands:
      - export IMAGE="ghcr.io/$${USERNAME}/micro-tracking:latest"
      - echo "$${TOKEN}" | docker login ghcr.io -u "$${USERNAME}" --password-stdin
      - docker build -t "$IMAGE" .
      - docker push "$IMAGE"

  deploy:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/serviciosjavi:/srv/serviciosjavi
    environment:
      USERNAME:
        from_secret: GHCR_USERNAME
      TOKEN:
        from_secret: GHCR_TOKEN
      TRACKING_NOTIFICATION_EMAIL:
        from_secret: TRACKING_NOTIFICATION_EMAIL
      RESEND_API_KEY:
        from_secret: RESEND_API_KEY
    commands:
      - cd /srv/serviciosjavi/microtracking
      - echo "$${TOKEN}" | docker login ghcr.io -u "$${USERNAME}" --password-stdin
      - docker compose pull
      - docker compose up -d
