server:
  port: 5555
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    context-path: /
  tomcat:
    max-threads: 10
    min-spare-threads: 1
    connection-timeout: 20000

spring:
  application:
    name: micro-tracking

  web:
    cors:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:5555/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Email donde recibirás las notificaciones
tracking:
  notification:
    email: ${TRACKING_NOTIFICATION_EMAIL:}

# Enlace con Resend
resend:
  api-key: ${RESEND_API_KEY:}
  from: "onboarding@resend.dev"
